version: "3"

services:
  redis:
    image: "redis:alpine"
    container_name: cache
    expose:
      - 6379
    ports:
    - "6379:6379"
      
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on: [redis]
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - REDIS_URL=redis://cache
      - GRAPHQL_ENDPOINT=http://graphql-engine:8080/v1/graphql
    ports:
      - "80:1124"
    volumes:
      - .:/home/node/xenovo
    command: /home/node/node_modules/.bin/nodemon server.js

networks:
  default:
    external:
      name: graphql_default

