version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:1124"
    volumes:
      - .:/home/node/xenovo
      - node_modules:/home/node/xenovo/node_modules
    networks:
      - app-network
    command: /home/node/xenovo/node_modules/.bin/nodemon server.js

networks:
  app-network:
    driver: bridge

volumes:
  node_modules: 